name: Deploy on Self-Hosted Runner

on:
  workflow_run:
    workflows: ["Build and Push to GHCR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest image
        run: docker pull ghcr.io/${{ github.repository_owner }}/opsw:latest

      - name: Stop old container
        run: docker stop opsw-container || true && docker rm opsw-container || true

      - name: Run new container
        run: |
          docker run -d -p 8000:8000 --name opsw-container \
          ghcr.io/${{ github.repository_owner }}/opsw:latest
